##
## @section Common parameters
##

## @param {string} ACCEPT_EULA=Y - Accept the end-user licensing agreement
ACCEPT_EULA: "Y"

## @param {string} MSSQL_PID=Developer - Product ID (Developer, Express, Standard, Enterprise)
MSSQL_PID: "Developer"

## @param {string} MSSQL_AGENT_ENABLED=true - Enable SQL Server Agent
MSSQL_AGENT_ENABLED: "true"

## @param {string} sa_password=changepassword - SA password
sa_password: "changepassword"

## @param {string} storage_size=50Gi - Storage size for MSSQL data
storage_size: "50Gi"
